/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package convertidor;

import javax.swing.JOptionPane;

/**
 *
 * @author melod
 */
public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBit = new javax.swing.JTextField();
        txtByte = new javax.swing.JTextField();
        txtKilobyte = new javax.swing.JTextField();
        txtMegabyte = new javax.swing.JTextField();
        txtGigabyte = new javax.swing.JTextField();
        txtTerabyte = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 139));
        jLabel1.setText("CONVERSOR DE MEDIDAS INFORMATICAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 620, 26));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("bit (b):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 80, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("byte (B):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 120, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("kilobyte (kB):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setText("megabyte (MB):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 170, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setText("gigabyte (GB):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setText("terabyte (TB):");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 160, -1));

        txtBit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBitActionPerformed(evt);
            }
        });
        getContentPane().add(txtBit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 230, -1));

        txtByte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtByte, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 230, -1));

        txtKilobyte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKilobyte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKilobyteActionPerformed(evt);
            }
        });
        getContentPane().add(txtKilobyte, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 230, -1));

        txtMegabyte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMegabyte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMegabyteActionPerformed(evt);
            }
        });
        getContentPane().add(txtMegabyte, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 230, -1));

        txtGigabyte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGigabyte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGigabyteActionPerformed(evt);
            }
        });
        getContentPane().add(txtGigabyte, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 230, -1));

        txtTerabyte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtTerabyte, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 230, -1));

        btnCalcular.setBackground(new java.awt.Color(0, 0, 255));
        btnCalcular.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, -1, -1));

        btnBorrar.setBackground(new java.awt.Color(255, 0, 0));
        btnBorrar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/convertidor/a1.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        txtBit.setText("");
    txtByte.setText("");
    txtKilobyte.setText("");
    txtMegabyte.setText("");
    txtGigabyte.setText("");
    txtTerabyte.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try {
        double bits = 0;

        if (!txtBit.getText().isEmpty()) { // bit
            bits = Double.parseDouble(txtBit.getText());
        } else if (!txtByte.getText().isEmpty()) { // byte
            bits = Double.parseDouble(txtByte.getText()) * 8;
        } else if (!txtKilobyte.getText().isEmpty()) { // KB
            bits = Double.parseDouble(txtKilobyte.getText()) * 8 * 1024;
        } else if (!txtMegabyte.getText().isEmpty()) { // MB
            bits = Double.parseDouble(txtMegabyte.getText()) * 8 * 1024 * 1024;
        } else if (!txtGigabyte.getText().isEmpty()) { // GB
            bits = Double.parseDouble(txtGigabyte.getText()) * 8 * 1024 * 1024 * 1024;
        } else if (!txtTerabyte.getText().isEmpty()) { // TB
            bits = Double.parseDouble(txtTerabyte.getText()) * 8 * 1024 * 1024 * 1024 * 1024;
        }

        // Ahora convertimos de bits a todas las unidades
        double bytes = bits / 8;
        double kb = bytes / 1024;
        double mb = kb / 1024;
        double gb = mb / 1024;
        double tb = gb / 1024;

        // Mostramos resultados en los campos
        txtBit.setText(String.valueOf(bits));
        txtByte.setText(String.valueOf(bytes));
        txtKilobyte.setText(String.valueOf(kb));
        txtMegabyte.setText(String.valueOf(mb));
        txtGigabyte.setText(String.valueOf(gb));
        txtTerabyte.setText(String.valueOf(tb));

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
                                           

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtBitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBitActionPerformed

    private void txtKilobyteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilobyteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilobyteActionPerformed

    private void txtMegabyteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMegabyteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMegabyteActionPerformed

    private void txtGigabyteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGigabyteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGigabyteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtBit;
    private javax.swing.JTextField txtByte;
    private javax.swing.JTextField txtGigabyte;
    private javax.swing.JTextField txtKilobyte;
    private javax.swing.JTextField txtMegabyte;
    private javax.swing.JTextField txtTerabyte;
    // End of variables declaration//GEN-END:variables
}
